### ISSUE TITLE
Don't have metaball.sketchplugin inside zip file

### ISSUE THREAD

**Issue by Zolotarskyi** [mheesakkers/sketch-plugin-metaball#1]
Don't have metaball.sketchplugin inside zip file
<img width="467" alt="Screenshot 2019-12-15 at 16 03 53" src="https://user-images.githubusercontent.com/47469257/70863795-7e9aa780-1f54-11ea-8b43-3a930bd1518e.png">

**Comment by mheesakkers** [comment]
Hi Zolotarskyi, there is indeed no .zip file in the source of the project. There's a seperate release link in the Readme and under the Releases tab of the Repo.

Here's the link:
https://github.com/mheesakkers/sketch-plugin-metaball/releases/latest/download/metaball.sketchplugin.zip
