### ISSUE TITLE
Plugin does not work on Sketch 71.1

### ISSUE THREAD

**Issue by llewellynathan** [mheesakkers/sketch-plugin-metaball#9]
I'm using Sketch 71.1. The plugin does not work even after restarting Sketch.

**Comment by mheesakkers** [comment]
Hi! Will need to look into this, seems that Sketch changed its inner workings.

**Comment by llewellynathan** [comment]
When trying the plugin I used two circles of the same size. This does not work. Based on doing that I figured the plugin was broken and reported this issue. A friend later pointed out that the plugin only works with circles of different sizes. My apologies for the false alarm.

**Comment by mheesakkers** [comment]
No problem! For circles of the same size you could draw a rectangle of a line with the stroke width of the circles radius/diameter ;)

**Comment by llewellynathan** [comment]
Yes, I'm a little embarrassed that it took me many hours yesterday to figure that out. haha
